name: chat
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.5.0
dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^5.2.1
  firebase_auth: ^5.1.4
  firebase_core: ^3.3.0
  firebase_messaging: ^15.2.1
  firebase_storage: ^12.4.2
  firebase_database: ^11.3.1
  firebase_app_check: ^0.3.2+6
  google_fonts: ^6.2.1
  shared_preferences: ^2.4.0
  flutter_secure_storage: ^9.2.2
  cupertino_icons: ^1.0.8
  flutter_dotenv: ^5.1.0
  get: ^4.6.6
  google_sign_in: ^6.2.1
  intl: ^0.20.1
  iconsax_plus: ^1.0.0
  permission_handler: ^11.4.0
  http: ^1.2.2
  dio: ^5.8.0+1
  pointycastle: ^4.0.0
  flutter_local_notifications: ^19.2.0
  sqflite: ^2.4.1
  path_provider: ^2.1.5
  connectivity_plus: ^6.1.2
  socket_io_client: ^3.0.2
  image_picker: ^1.1.2
  file_picker: ^10.1.9
  emoji_picker_flutter: ^4.3.0
  video_player: ^2.9.3
  chewie: ^1.10.0
  video_thumbnail: ^0.5.6
  rxdart: ^0.28.0
  record: ^6.0.0
  speech_to_text: ^7.0.0
  camerawesome: ^2.3.0
  open_filex: ^4.7.0
  image_editor_plus: ^1.0.6
  agora_rtc_engine: ^6.5.2
  url_launcher: ^6.2.5
  package_info_plus: ^8.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/img/
