// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7i2giC-YgGXl51eZdeOxHjABhbQhpihc',
    appId: '1:340738288883:web:af83a76185a16f10131b86',
    databaseURL:
        "https://chatkuyyy-default-rtdb.asia-southeast1.firebasedatabase.app",
    messagingSenderId: '340738288883',
    projectId: 'chatkuyyy',
    authDomain: 'chatkuyyy.firebaseapp.com',
    storageBucket: 'chatkuyyy.appspot.com',
    measurementId: 'G-FJJ9WYKCR1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyMUg91y_TNVQTImCgM1PT4G36csvAQPw',
    appId: '1:340738288883:android:c27dd0006aec8be9131b86',
    databaseURL:
        "https://chatkuyyy-default-rtdb.asia-southeast1.firebasedatabase.app",
    messagingSenderId: '340738288883',
    projectId: 'chatkuyyy',
    storageBucket: 'chatkuyyy.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWH7-dWuSj8g9HsP1lIbSpdOz0RUQpL-0',
    appId: '1:340738288883:ios:2e1eb31e179c6254131b86',
    databaseURL:
        "https://chatkuyyy-default-rtdb.asia-southeast1.firebasedatabase.app",
    messagingSenderId: '340738288883',
    projectId: 'chatkuyyy',
    storageBucket: 'chatkuyyy.appspot.com',
    androidClientId:
        '340738288883-1rlatp4bmk7bhc9go8oqc1s9hn88ts33.apps.googleusercontent.com',
    iosClientId:
        '340738288883-9t3vcjjvv5qmartbqu0srcli0l83542t.apps.googleusercontent.com',
    iosBundleId: 'com.example.chat',
  );
}
